name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Label PR
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          const labelsToAdd = ["needs-review"]; // Labels to add
          const prNumber = context.payload.pull_request.number;

          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            labels: labelsToAdd,
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

